# Reine Datenbeschreibung der Items. Keine Importe von main.py, damit
# es keine zirkulären Importe gibt.
ITEMS_DATA = [
    {
        "name": "Joghurt-Frühstück",
        "calories_per_portion": 360.9,
        "fat_per_portion": 15.63,
        "carbs_per_portion": 36.24,
        "protein_per_portion": 15.8,
        "fibre_per_portion": 5.72,
        "salt_per_portion": 0.4,
        "meal_types": ["BREAKFAST", "DINNER"],
        "max_portions": 2.0,
    },
    {
        "name": "Reis",
        "calories_per_portion": 867.5,
        "fat_per_portion": 7,
        "carbs_per_portion": 175,
        "protein_per_portion": 18.25,
        "fibre_per_portion": 14.75,
        "salt_per_portion": 0.03,
        "meal_types": ["LUNCH"],
        "lunch_role": "MAIN",
        "max_portions": 1.0,
    },
    {
        "name": "Seitan",
        "calories_per_portion": 120,
        "fat_per_portion": 2,
        "carbs_per_portion": 5,
        "protein_per_portion": 25,
        "fibre_per_portion": 0,
        "salt_per_portion": 0,
        "meal_types": ["LUNCH"],
        "lunch_role": "SIDE",
        "max_portions": 2.0,
    },
    {
        "name": "Toasty",
        "calories_per_portion": 338.8,
        "fat_per_portion": 13.86,
        "carbs_per_portion": 29.4,
        "protein_per_portion": 23.80,
        "fibre_per_portion": 0,
        "salt_per_portion": 2.38,
        "meal_types": ["LUNCH"],
        "lunch_role": "SIDE",
        "max_portions": 1.0,
    },
    {
        "name": "Nudeln",
        "calories_per_portion": 368,
        "fat_per_portion": 1.5,
        "carbs_per_portion": 75,
        "protein_per_portion": 12,
        "fibre_per_portion": 0,
        "salt_per_portion": 0.01,
        "meal_types": ["LUNCH"],
        "lunch_role": "MAIN",
        "max_portions": 3.0,
    },
]
